name: Codegen

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  codegen:
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} ${{ matrix.os }}
    strategy:
      matrix:
        java: [17]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'corretto'

      - name: Log Kotlin version
        run: |
          which kotlin
          kotlin -version

      - name: Clean and Build
        run: ./gradlew clean build -Plog-tests

      - name: Ensure there are no changes after building (e.g. the Weather SDK)
        run: |
          git diff
          test -z "$(git diff)"

      - name: Log Swift version
        if: ${{matrix.os}} == "macos-latest"
        run: |
          which swift
          swift --version

      - name: Build test projections (e.g. the Weather SDK)
        if: ${{matrix.os}} == "macos-latest"
        run: |
          ./scripts/ci_steps/build_test_projections.sh
