name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout smithy-swift
      - uses: actions/checkout@v2
      - name: Checkout aws-crt-swift
      - uses: actions/checkout@v2
        with:
          repository: awslabs/aws-crt-swift
          path: ~/Projects/Amplify/SwiftSDK
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build Client Runtime
        run: cd ClientRuntime && swift build
      - name: Test Client Runtime
        run: |
          swift test --enable-code-coverage
          bash <(curl -s https://codecov.io/bash)
      - name: Run SwiftLint (Only files changed in the PR) in Client Runtime
        uses: norio-nomura/action-swiftlint@3.1.0
        env:
          DIFF_BASE: ${{ github.base_ref }}
      - name: Grant execute permission for gradlew
        run: cd .. && chmod +x gradlew
      - name: Build
        run: ./gradlew build -x test -x jvmTest
      - name: Unit Tests
        run: ./gradlew test rootAllTest
      - name: Lint
        run: ./gradlew ktlint